# Generated by Django 4.0.5 on 2022-06-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_id_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_total',
            field=models.IntegerField(default=0),
        ),
    ]
